export const images = {
  splash: '',
  // splash: require('../assets/images/backgrounds/Splash.png'),
  // defaultBackground: require('../assets/images/backgrounds/default_background.png'),
  // bibotBackground: require('../assets/images/backgrounds/bibot_background.png'),
  // tutorialBackground_1: require('../assets/images/backgrounds/tutorial_background_1.png'),
  // tutorialBackground_2: require('../assets/images/backgrounds/tutorial_background_1.png'),
  // tutorialBackground_3: require('../assets/images/backgrounds/tutorial_background_3.png'),
  // noConnection: require('../assets/images/icons/no_connection.png'),
  // newUpdate: require('../assets/images/icons/new_update.png'),
  // defaultUserGirl: require('../assets/images/icons/default_user_girl.png'),
  // homeBackground: require('../assets/images/backgrounds/home_background.png'),
  // homeBackground2: require('../assets/images/backgrounds/home_background2.png'),
  // homeBackground3: require('../assets/images/backgrounds/home_background3.png'),
  // homeBackground4: require('../assets/images/backgrounds/home_background4.png'),
  // homeBackground5: require('../assets/images/backgrounds/home_background5.png'),
  // bibotTextIcon: require('../assets/images/icons/bibot_text_icon.png'),
  // homeStarsIcon: require('../assets/images/icons/home_stars_icon.png'),
  // bookCover: require('../assets/images/backgrounds/book_cover_example.png'),
  // bookCover2: require('../assets/images/backgrounds/book_cover_example2.png'),
  // bookCover3: require('../assets/images/backgrounds/book_cover_example3.png'),
  // bookCover4: require('../assets/images/backgrounds/book_cover_example4.png'),
  // livroSemCapa: require('../assets/images/backgrounds/book_cover_example2.png'),
};
